// <auto-generated />
namespace SM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Email_field_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email_field_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201901310824020_Email_field_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
